### ISSUE TITLE
Missing a list

### ISSUE THREAD

**Issue by akaAMAZING** [arturino009/POEcluster#1]
Hi there, got enticed by your description of this tool and thought it would be the holy grail that I was searching for 😄 

However, it seems to be missing a list. Would it be possible to share it so I can experience what this can do?

Thank you!

**Comment by arturino009** [comment]
I added the missing list. I actually forgot to commit it lol. But it's outdated now (Harvest league), because it seems all notables became rarer, so all percentages are wrong. I wrote them all manually, so its a lot to change. I just couldn't find a convienent way to get all percentages and categories etc.
