### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by gdneye** [arturino009/POEcluster#3]
Hey, not sure if you're still supporting this but I've been working on getting it installed.  I got all of the dependencies set up and the program ran but it is running into an error on line 89:

Traceback (most recent call last):
  File "C:\Cluster\apiM\apiMaybe.py", line 89, in <module>
    current_exa_price = round(float(res[0].contents[0]))                                             #current exa price https://poe.ninja/challenge/currency/exalted-orb
IndexError: list index out of range

Thanks!

**Comment by arturino009** [comment]
Yes, that's expected. It hasn't been updated to the newest league yet and it doesn't work at all. I know that I need to download stats.json file again from the official website, and probably redownload all the cluster pages from craftofexile (I think some weightings changed and some notables were removed),  because this league added a lot of new items. I might even fix that today or tomorrow because you somehow even found this repo

**Comment by gdneye** [comment]
Yeah I found it just by searching github for things like "POE", "Path of Exile", etc.  Way back in the day before the trade API white list I heard about sniper programs and went searching.  I eventually found a good sniper program on github that served me well until they set up the white list.  

I was actually looking for an indexer.  I wanted to basically do the same thing you did here but with Watcher's Eyes.  I'm not a programmer, but I was looking for a data dump of listed Watcher's Eye prices then I was just planning to build out formula's in Excel (or maybe some SQL code) to automate the rest.  Essentially I wanted to get an output for 2 mod Watcher's Eye combos.  Then use those results to manually set up live searches.

Extremely similar to what you've done here with Cluster Jewels.  While searching I ran across your program and figured I'd see if I could get it running since it was so similar to what I was planning to do anyways.

If there is any manual work involved in getting that stats.json file and/or redownloading the cluster pages from craftofexile I'd be happy to help.  It sounds like the stats.json is probably just a single page, but I could go through all of the craftofexile pages and save them in whatever format you would need.

Anyways, thanks for the project!  I'm looking forward to trying it out.

**Comment by arturino009** [comment]
So, I updated the app. It should work now.  Updated the stats.json file, and some minor changes in the code. Things like tries, profit, PPT (ProfitPerTry when crafting with alts, augments and regals based on average price of first 10 listings), LPPT (LegitProfitPerTry based on the first 2 listings) might not be correct, because I'm not sure that weights of individual mods changed and I haven't updated the craftofexile pages, but AFAIK there weren't big changes this league. Prices and profit for crafting also probably aren't correct. But the average price and first(average of first 2 entries) should be correct.
Be warned that listing all the 2 mod combinations for medium cluster jewels might take like 10 minutes or more, because there are like fucktons of combinations and im legit going the fastest way not to get rate limited. And also it shows only combinations with 10 or more active listings.
The error you were getting is the problem requests_html module. Most of the time it wasn't waiting until the page fully loaded, so search for elements returned nothing. Currently I made a temporary fix and made exalt and alch prices fixed in case of an error. Probably will need to replace this module with something else.
And also, do you mind telling how the heck you actually managed to install TkTreectrl? I did it like half a year ago and don't know how I did it, but today spent like 3 hours trying to install it onto another machine. 
Glad that you are interested! Hope that you like exploring the project. What you want to do is kinda what I have in this project (except I have a lot more that you don't need). It all boils down to having a list of all mods for watchers eye's, then getting each mod it's correct "mod value" from stats.json file for the trade website. Then make a list of all those double combinations of "mod values", and send a POST request to the trade website with each one. It will return all the listings for specified combination, but you can only request the prices for 10 at a time. Then you can work with this data as you want.

**Comment by gdneye** [comment]
Thanks for updating it!  I will run the new version and let you know how it goes.  And yeah I understand the issue with it taking 10 minutes, I had already considered how I might have a similar issue with Watcher's Eyes for exactly the same reason.

Regarding the issue with the requests_html module.  Again, I'm not a programmer, but trouble-shooting code has been part of a job I've had previously... Is it possible to just add in a delay so that the website will load before pulling the Exalt/Alch price?  This isn't really an issue for me.  I can read code well enough that I can go in and manually change the price, I'm just thinking of how you could solve the issue so you don't have to manually update that going forwards.

**Tktree**
My first guess for the issue you might be having with tktreectrl is using the wrong version?  When I googled tktreectrl most of the links I took eventually directed me to this link.

https://sourceforge.net/projects/tktreectrl/

However that link was last updated in 2013 and I believe it is deprecated.  There is another tktreectrl link at sourceforge

https://sourceforge.net/projects/tkintertreectrl/

The files on the second project worked just fine.  All I had to do was navigate to the directory where I downloaded it and then installed it manually (I believe I just downloaded, opened a cmd prompt, cd'd to where I unzipped it and then used 'python setup.py install').

If that doesn't work let me know and I will set it all up again on my PC (right now I only have it on my laptop).  But going through the steps again I should be able to figure out what you might have missed.

**Watcher's Eye**
I might be able to modify your project to do the same for Watcher's Eyes, but I'm a bit skeptical.  Watcher's Eye's (especially good, dual mod ones) can be fairly rare and may not sit on the market for very long, meaning I might not have enough data if all I see is a snapshot of the market.  I'm still working on trying to get an indexer running for that project since an indexer will show me ALL Watcher's Eyes that have gone on the market (I plan to just start the API river at the beginning of this Heist league, so I won't have to parse through all of the old info).  But once I have that data I'll do something similar to what you've done here to attempt to calculate true prices and then ofc set up live searches for underpriced ones.  If you are interested I can update you once I have an indexer working.  You're helping me out here so I don't have any issue sharing any progress I make on that project with you.

Edit:  I may have spoken too soon.  Ran the program just now and ran into a tktree problem.  Will research and update you.

**Comment by gdneye** [comment]
OK so regarding tktree... ignore what I said earlier.  I was finally able to get it to work by copying the older file, the one that was last updated in 2013, into the Python\Python39\TCL folder.  (This one: https://sourceforge.net/projects/tktreectrl/files/tktreectrl/tktreectrl-2.4.1/)

No CLI install needed.  Just copy/pasted the entire thing into the TCL folder.  If you don't have the TCL folder yet I'm pretty sure I did have to install that through command line but I did a lot of messing around so I'm not 100% certain.  It may have come pre-installed with Python 3.9.

Once I installed that it ran one mod jewels correctly.
