### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by akaAMAZING** [arturino009/POEcluster#8]
Hi again! Great effort, I love what you've done with this.

However, it gets rate limited constantly after about two minutes of use. How would I go about avoiding this in the future?

There are tools like Awakened POE Trade that throttle themselves as to not trigger this limit.

Might there be a way to implement it into this program too so that it could be functional as there is truly significant value behind it.

Let me know what I can do to help.

Thank you.

**Comment by arturino009** [comment]
Ok, so I investigated the rate limit rules. Exact rules: 5:10:60,15:60:300,30:300:1800.
The bad news are, I can only make 30 requests per 300 seconds (so 1 request every 10 seconds) without getting rate limited. Since this tool makes from 200 to 1200 requests continuously, we have to use the most limiting rule, so it will take a while.
I updated the tool so it won't get rate limited, but it's all I can do until the rate limit changes.
